### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'

### ISSUE THREAD

**Issue by O-O1024** [Drexubery/ViewCrafter#20]
```
!!! Exception during processing !!! 'VisionTransformer' object has no attribute 'input_patchnorm'
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/__init__.py", line 140, in gen_video
    self.pvd.nvs_single_view()
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/infer.py", line 161, in nvs_single_view
    diffusion_results = self.run_diffusion(render_results)
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/infer.py", line 95, in run_diffusion
    batch_samples = image_guided_synthesis(self.diffusion, prompts, videos, self.noise_shape, self.opts.n_samples, self.opts.ddim_steps, self.opts.ddim_eta, \
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/viewcrafter/utils/diffusion_utils.py", line 128, in image_guided_synthesis
    img_emb = model.embedder(img) ## blc
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/viewcrafter/lvdm/modules/encoders/condition.py", line 339, in forward
    z = self.encode_with_vision_transformer(image)
  File "/root/ComfyUI/custom_nodes/ViewCrafter-ComfyUI/viewcrafter/lvdm/modules/encoders/condition.py", line 346, in encode_with_vision_transformer
    if self.model.visual.input_patchnorm:
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'
```

**Comment by Drexubery** [comment]
Hi, please refer to the solution here https://github.com/Drexubery/ViewCrafter/issues/10#issuecomment-2347825002
