### ISSUE TITLE
sh run.sh: IndexError: pop from empty list

### ISSUE THREAD

**Issue by zhujiagang** [Drexubery/ViewCrafter#26]
Thanks for sharing your excellent work. I encounter a problem when running `sh run.sh`.
```
(viewcrafter) :~/codes/ViewCrafter$ sh run.sh
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
... loading model from ./checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth
instantiating : AsymmetricCroCo3DStereo(enc_depth=24, dec_depth=12, enc_embed_dim=1024, dec_embed_dim=768, enc_num_heads=16, dec_num_heads=12, pos_embed='RoPE100', patch_embed_cls='PatchEmbedDust3R', img_size=(512, 512), head_type='dpt', output_mode='pts3d', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), landscape_only=False)
<All keys matched successfully>
/mnt/data-2/users/zhujiagang/miniconda3/envs/viewcrafter/lib/python3.9/site-packages/torch/cuda/__init__.py:155: UserWarning:
NVIDIA H20 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H20 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Global seed set to 123
AE working on z of shape (1, 4, 32, 32) = 4096 dimensions.
>>> model checkpoint loaded.
>> Loading a list of 1 images
 - adding test/images/boy.png with resolution 1024x576 --> 512x288
 (Found 1 images)
>> Inference with model on 2 image pairs
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.91s/it]
Traceback (most recent call last):
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/inference.py", line 16, in <module>
    pvd = ViewCrafter(opts)
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/viewcrafter.py", line 38, in __init__
    self.run_dust3r(input_images=self.images)
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/viewcrafter.py", line 47, in run_dust3r
    loss = scene.compute_global_alignment(init='mst', niter=self.opts.niter, schedule=self.opts.schedule, lr=self.opts.lr)
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/./extern/dust3r/dust3r/cloud_opt/base_opt.py", line 301, in compute_global_alignment
    init_fun.init_minimum_spanning_tree(self, niter_PnP=niter_PnP)
  File "/mnt/data-2/users/zhujiagang/miniconda3/envs/viewcrafter/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/./extern/dust3r/dust3r/cloud_opt/init_im_poses.py", line 73, in init_minimum_spanning_tree
    pts3d, _, im_focals, im_poses = minimum_spanning_tree(self.imshapes, self.edges,
  File "/mnt/data-2/users/zhujiagang/codes/ViewCrafter/./extern/dust3r/dust3r/cloud_opt/init_im_poses.py", line 136, in minimum_spanning_tree
    score, i, j = todo.pop()
IndexError: pop from empty list
```
Do you know hwo to solve it? Thank you very much.

**Comment by zhujiagang** [comment]
When I change the torch version to torch2.4, the problem is solved. My gpu is H20.
